### ISSUE TITLE
Asp.Net Core 3.1 support

### ISSUE THREAD

**Issue by robyvandamme** [jsreport/jsreport-dotnet-aspnetcore#13]
jsreport.AspNetCore references the Mcrosoft.AspNetCore.Http 2.2.2 and Microsoft.AspNetCore.Mvc 2.2.0 packages

I noticed a pull request to add 3.0 support, but since 3.1 is the LTS release: is it the intention to support Asp.Net Core 3.1 at some point in the near future?

**Comment by pofider** [comment]
We take a look when releasing the 2.7.0 in some days.
I believe there will be no issue.

**Comment by ghost** [comment]
Asp.Net Core 3.1 support was added in this pull request: #14. I think this issue can be closed.
