### ISSUE TITLE
Save report to a File

### ISSUE THREAD

**Issue by hieutran106** [jsreport/jsreport-dotnet-aspnetcore#2]
I want to both save report to a file and send to client so I use that code inside an Action in my Controller
`HttpContext.JsReportFeature().Recipe(Recipe.PhantomPdf).OnAfterRender((report) =>
                {
                    Stream content = report.Content;
                    string path = @"test.pdf";
                    using (FileStream fs = System.IO.File.Create(path))
                    {
                        content.CopyTo(fs);
                    }
                });
`
However, it only save report to a file on server, not send the report content to Client.

**Comment by KhalilMohammad** [comment]
[This issue is quite similar](https://github.com/jsreport/jsreport-dotnet-example-webapp/issues/4)

**Comment by JeanCollas** [comment]
You may have a look at this pull request:
https://github.com/JeanCollas/jsreport-dotnet-aspnetcore/blob/master/README.md
Which provides an alternative solution.

**Comment by pofider** [comment]
This is now part of the docs
https://jsreport.net/learn/dotnet-aspnetcore#save-to-file
