### ISSUE TITLE
Error rendering report

### ISSUE THREAD

**Issue by pedrommuller** [jsreport/jsreport-dotnet-aspnetcore#8]
I'm trying to run the local report in an azure app service, the app service is running on, the general settings are the following:

![capture](https://user-images.githubusercontent.com/16243859/48240773-b0c4f780-e399-11e8-889d-c8564cdaba14.png)

looking at the application insigths I'm getting is the following error:

> Error rendering report: A critical error occurred while trying to execute the render command: spawn UNKNOWN (1). caused by error (1) -> meta = {"remoteStack":"Error: spawn UNKNOWN\n at _errnoException (util.js:1022:11)\n at ChildProcess.spawn (internal/child_process.js:323:11)\n at Object.exports.spawn (child_process.js:503:9)\n at Function.launch (jsreportRuntime.js:315048:40)\n at <anonymous>"}, stack = Error: at responseToBuffer ([eval]:45649:29) at concat ([eval]:45702:40) at ConcatStream.<anonymous> ([eval]:14359:43) at emitNone (events.js:111:20) at ConcatStream.emit (events.js:208:7) at finishMaybe ([eval]:92007:14) at afterWrite ([eval]:91869:3) at _combinedTickCallback (internal/process/next_tick.js:144:20) at process._tickCallback (internal/process/next_tick.js:180:9)

> Exception type | jsreport.Local.JsReportBinaryException

> Failed method	jsreport.Local.Internal.LocalUtilityReportingService+<RenderAsync>d__10.MoveNext

Any ideas?

I'm using the windows birary and it works on my machine @.@

**Comment by pofider** [comment]
I have done some tests and unfortunately jsreport.Local doesn't work in the azure web apps on windows. See this more documented here
https://jsreport.net/learn/dotnet-local#azure-web-apps
